### ISSUE TITLE
Support N-1 version selection for Falcon Container

### ISSUE THREAD

**Issue by isimluk** [CrowdStrike/falcon-operator#105]

**Comment by cs-shadowbq** [comment]
So should the operator automatically start the rolling update if the operator identifies a change to `n`,`n-1`, `n-2`? The registry does not have `n` or n-like tags. This would be similar to having `latest` tags. 

Note: Although `us-1` I believe does have `latest` not all the CrowdStrike cloud container registries even have the `latest` tag. In order to get the  current `n-#` settings in falcon, the traditional RESTAPI might be queried for the current linux `n-#` settings.

**Comment by isimluk** [comment]
> In order to get the current n-# settings in falcon, the traditional RESTAPI might be queried for the current linux n-# settings.

Which rest API end-point would you suggest to use?

**Comment by redhatrises** [comment]
Closing as there is no planned movement on this.
