### ISSUE TITLE
[FEATURE REQUEST] Ability to Define Node-Sensor Limits/Requests

### ISSUE THREAD

**Issue by jwhitcraft** [CrowdStrike/falcon-operator#340]
It would be beneficial to monitoring our clusters to have CPU and Memory Request and Limits set on these pods so they are limited into how much resources they can take up per node.

Right now with nothing defined they can consume as much as they want, which is bad when trying to manage the cluster resources.

**Comment by falcon-pioupiou** [comment]
are you asking for Falcon-Container (sidecar) ? or Falcon-sensor as DaemonSet ?

For Falcon-Container you can do it actually : https://github.com/CrowdStrike/falcon-operator/blob/main/config/samples/falcon_v1alpha1_falconcontainer-all-options.yaml#L43-L49 

For falcon-sensor as DaemonSet it's risky because Kubernetes could kill the pod if resources are too low. This sensor was designed to consume few resources.

**Comment by jwhitcraft** [comment]
This was for the Flacon-sensor as a DaemonSet

I can see you point about k8s killing it, if it runs out of resources. 


Just a though I had, but we can close this.
