### ISSUE TITLE
Running As Non-Root

### ISSUE THREAD

**Issue by ibanks** [CrowdStrike/falcon-operator#604]
This is just a general question about the falcon operator. If someone could please explain the use case for the product having to run as a privileged user if deployed within a kubernetes or openshift environment.

Is it possible that the service can run as a non-privileged user? Thanks in advance. :-)

**Comment by redhatrises** [comment]
Can you provide more info on which part of the operator that you are referring to since there are many workloads of varying permissions that get deployed to a cluster?

**Comment by ibanks** [comment]
@redhatrises I really appreciate your prompt reply. Thanks so much. So there is another team that manages the falcon operator deployment within kubernetes / openshift and as result would be more familiar with the internals. The questions that I ask are just based on somethings that I've observed about the service.

To answer your question about which part of the operator, I believe it is the falcon node sensor which looks like it is deployed as a DaemonSet on each node in the cluster.

Now, based on your statement of "run as a native process on nodes", I believe you are speaking about a daemon running on the node that is managed by systemd on a Linux platform correct? If this is the case, from my understanding of how systemd works, you can manage a systemd process as a specific non-privileged user. Would that be the only reason that this security product would be configured to run with root privileges?

Btw, I am asking these questions because I am a part of a security team that manages how microservice architecture runs by setting guardrails.

**Comment by redhatrises** [comment]
It kinda is a misnomer for security software to be unprivileged. Since K8s manages the pods and containers, systemd doesn't manage the falcon sensor process on the nodes; K8s and the container runtime do. The sensor is privileged for several reasons:

1. It runs as a K8s native resource on each of the nodes.
2. Has to be able to look at all the processes including containers running
3. Has to be able to see what files/folder exist which RBAC and FACL might prevent access to.
4. For effective detection and prevention, can't run without privileges as you might not be able to see what is going on in the first place thereby missing an attacker's activity.
5. It runs as a kernel module or uses eBPF. Both require full root privileges. Full stop there.
6. Most K8s security recommendations to run as non-root are not written for many infrastructure services like filesystem managers and security but because many people were operating with bad practices and running with privileges for web services, etc.

**Comment by ibanks** [comment]
Thanks @redhatrises for providing your insight on this. It does make more sense now.
